version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./compose/production/nginx/app.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: ./compose/production/web/Dockerfile
    container_name: web
    volumes:
      - ./app:/app
    expose:
      - "8000"
